"""sprint 3 application and usage

Revision ID: 9fdd13a3da4f
Revises: ea0ba84cd47c
Create Date: 2026-09-17 18:05:10.079377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdd13a3da4f'
down_revision: Union[str, None] = 'ea0ba84cd47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'slug', name='uq_application_project_slug')
    )
    op.create_index(op.f('ix_applications_project_id'), 'applications', ['project_id'], unique=False)
    op.add_column('ai_workloads', sa.Column('application_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_ai_workloads_application_id'), 'ai_workloads', ['application_id'], unique=False)
    op.create_foreign_key(
        'fk_ai_workloads_application_id_applications',
        'ai_workloads', 'applications', ['application_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_ai_workloads_application_id_applications', 'ai_workloads', type_='foreignkey'
    )
    op.drop_index(op.f('ix_ai_workloads_application_id'), table_name='ai_workloads')
    op.drop_column('ai_workloads', 'application_id')
    op.drop_index(op.f('ix_applications_project_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
