"""sprint 6 client instrumentation context

Revision ID: b5fd184c5f53
Revises: 9fdd13a3da4f
Create Date: 2026-09-18 14:43:43.353099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fd184c5f53'
down_revision: Union[str, None] = '9fdd13a3da4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_workloads', sa.Column('client_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_workloads', 'client_context')
    # ### end Alembic commands ###
