"""initial schema

Revision ID: ea5cca7ca239
Revises: 
Create Date: 2026-09-17 13:09:30.168172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5cca7ca239'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('methodologies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methodologies_version'), 'methodologies', ['version'], unique=True)
    op.create_table('methodology_factors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('factor_id', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('hardware', sa.String(length=128), nullable=True),
    sa.Column('value_min', sa.Float(), nullable=False),
    sa.Column('value_max', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('evidence_level', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('accounting_boundary', sa.String(length=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('methodology_version', sa.String(length=32), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methodology_factors_factor_id'), 'methodology_factors', ['factor_id'], unique=True)
    op.create_index('ix_methodology_factors_lookup', 'methodology_factors', ['metric', 'provider', 'model', 'modality', 'activity_type'], unique=False)
    op.create_index(op.f('ix_methodology_factors_methodology_version'), 'methodology_factors', ['methodology_version'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('supported_modalities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('modalities', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('methodology_version', sa.String(length=32), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'name', 'version', name='uq_model_provider_name_version')
    )
    op.create_index(op.f('ix_models_provider_id'), 'models', ['provider_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('ai_workloads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('video_seconds', sa.Float(), nullable=True),
    sa.Column('video_resolution', sa.String(length=32), nullable=True),
    sa.Column('audio_seconds', sa.Float(), nullable=True),
    sa.Column('tool_calls', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('parent_workload_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_workload_id'], ['ai_workloads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_workloads_organization_id'), 'ai_workloads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_workloads_parent_workload_id'), 'ai_workloads', ['parent_workload_id'], unique=False)
    op.create_index(op.f('ix_ai_workloads_project_id'), 'ai_workloads', ['project_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_project_id'), 'api_keys', ['project_id'], unique=False)
    op.create_table('estimates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workload_id', sa.String(length=64), nullable=False),
    sa.Column('energy_status', sa.String(length=20), nullable=False),
    sa.Column('energy_min_wh', sa.Float(), nullable=True),
    sa.Column('energy_max_wh', sa.Float(), nullable=True),
    sa.Column('water_status', sa.String(length=20), nullable=False),
    sa.Column('water_min_ml', sa.Float(), nullable=True),
    sa.Column('water_max_ml', sa.Float(), nullable=True),
    sa.Column('carbon_status', sa.String(length=20), nullable=False),
    sa.Column('carbon_min_g', sa.Float(), nullable=True),
    sa.Column('carbon_max_g', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('evidence_level', sa.Integer(), nullable=True),
    sa.Column('accounting_boundary', sa.String(length=4), nullable=True),
    sa.Column('methodology_version', sa.String(length=32), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workload_id'], ['ai_workloads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimates_workload_id'), 'estimates', ['workload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimates_workload_id'), table_name='estimates')
    op.drop_table('estimates')
    op.drop_index(op.f('ix_api_keys_project_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_workloads_project_id'), table_name='ai_workloads')
    op.drop_index(op.f('ix_ai_workloads_parent_workload_id'), table_name='ai_workloads')
    op.drop_index(op.f('ix_ai_workloads_organization_id'), table_name='ai_workloads')
    op.drop_table('ai_workloads')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_models_provider_id'), table_name='models')
    op.drop_table('models')
    op.drop_table('providers')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_methodology_factors_methodology_version'), table_name='methodology_factors')
    op.drop_index('ix_methodology_factors_lookup', table_name='methodology_factors')
    op.drop_index(op.f('ix_methodology_factors_factor_id'), table_name='methodology_factors')
    op.drop_table('methodology_factors')
    op.drop_index(op.f('ix_methodologies_version'), table_name='methodologies')
    op.drop_table('methodologies')
    # ### end Alembic commands ###
