"""aifootprint - a thin, typed Python client for the AI Footprint API.

    from aifootprint import AIClient

    client = AIClient(api_key="afp_live_...")

See README.md for a full Quick Start. This package contains no
estimation, methodology, or ranking logic of its own - every number it
returns came directly from the AI Footprint API.
"""

from .client import AIClient
from .exceptions import (
    AIFootprintError,
    APIError,
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    NotFoundError,
    RateLimitError,
    TransportError,
    ValidationError,
)
from .models import (
    ActivityType,
    AggregateImpact,
    AggregateMetricRange,
    AIModel,
    ApiKey,
    ApiKeyCreated,
    ApiKeyList,
    Application,
    ApplicationEnvironment,
    ApplicationList,
    ApplicationStatus,
    BatchItemResult,
    BatchResult,
    BenchmarkDefinition,
    BenchmarkList,
    BenchmarkRunResult,
    CompareResult,
    ComparisonCandidate,
    ComparisonResultItem,
    Confidence,
    Denominator,
    ErrorDetail,
    Estimate,
    Event,
    Methodology,
    MetricRange,
    MetricStatus,
    Modality,
    NormalizationBasis,
    NormalizedMetricRange,
    NormalizedResourceIntensity,
    Organization,
    OrganizationBootstrap,
    PersistedEstimate,
    Project,
    ProjectList,
    ProjectStatus,
    Provider,
    UsageByActivityItem,
    UsageByActivityResult,
    UsageByApplicationItem,
    UsageByApplicationResult,
    UsageByModelItem,
    UsageByModelResult,
    UsageByProviderItem,
    UsageByProviderResult,
    UsageGranularity,
    UsagePeriod,
    UsageSummary,
    UsageTimeseriesPoint,
    UsageTimeseriesResult,
    Workload,
    WorkloadCounts,
    WorkloadPage,
)

__version__ = "0.1.0"

__all__ = [
    "AIClient",
    # Exceptions
    "AIFootprintError",
    "APIError",
    "AuthenticationError",
    "AuthorizationError",
    "ConflictError",
    "NotFoundError",
    "RateLimitError",
    "TransportError",
    "ValidationError",
    # Enums
    "ActivityType",
    "ApplicationEnvironment",
    "ApplicationStatus",
    "Confidence",
    "MetricStatus",
    "Modality",
    "NormalizationBasis",
    "ProjectStatus",
    "UsageGranularity",
    # Models
    "AIModel",
    "AggregateImpact",
    "AggregateMetricRange",
    "ApiKey",
    "ApiKeyCreated",
    "ApiKeyList",
    "Application",
    "ApplicationList",
    "BatchItemResult",
    "BatchResult",
    "BenchmarkDefinition",
    "BenchmarkList",
    "BenchmarkRunResult",
    "CompareResult",
    "ComparisonCandidate",
    "ComparisonResultItem",
    "Denominator",
    "ErrorDetail",
    "Estimate",
    "Event",
    "Methodology",
    "MetricRange",
    "NormalizedMetricRange",
    "NormalizedResourceIntensity",
    "Organization",
    "OrganizationBootstrap",
    "PersistedEstimate",
    "Project",
    "ProjectList",
    "Provider",
    "UsageByActivityItem",
    "UsageByActivityResult",
    "UsageByApplicationItem",
    "UsageByApplicationResult",
    "UsageByModelItem",
    "UsageByModelResult",
    "UsageByProviderItem",
    "UsageByProviderResult",
    "UsagePeriod",
    "UsageSummary",
    "UsageTimeseriesPoint",
    "UsageTimeseriesResult",
    "Workload",
    "WorkloadCounts",
    "WorkloadPage",
]
